/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Textbooked Backend API
 * Backend MVP API for textbook study planning and grading.
 * OpenAPI spec version: 1.0.0
 */
import type {
  CurrentUserDto,
  HealthGetHealth200
} from '../schemas';

import authGetMeMutator from '../axios';
import healthGetHealthMutator from '../axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getTextbookedBackendAPI = () => {
/**
 * @summary Get current authenticated user
 */
const authGetMe = (
    
 options?: SecondParameter<typeof authGetMeMutator>,) => {
      return authGetMeMutator<CurrentUserDto>(
      {url: `/auth/me`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Health check
 */
const healthGetHealth = (
    
 options?: SecondParameter<typeof healthGetHealthMutator>,) => {
      return healthGetHealthMutator<HealthGetHealth200>(
      {url: `/health`, method: 'GET'
    },
      options);
    }
  
return {authGetMe,healthGetHealth}};
export type AuthGetMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTextbookedBackendAPI>['authGetMe']>>>
export type HealthGetHealthResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTextbookedBackendAPI>['healthGetHealth']>>>
