/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Textbooked Backend API
 * Backend MVP API for textbook study planning and grading.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateOnboardingStudyPlanRequestDto,
  CreateOnboardingStudyPlanResponseDto,
  CurrentUserDto,
  HealthGetHealth200,
  OnboardingStatusDto,
  RepaceStudyPlanRequestDto,
  RepaceStudyPlanResponseDto
} from '../schemas';

import authGetMeMutator from '../axios';
import onboardingGetStatusMutator from '../axios';
import onboardingCreateStudyPlanMutator from '../axios';
import studyPlansRepaceMutator from '../axios';
import healthGetHealthMutator from '../axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const authGetMe = (
    
 options?: SecondParameter<typeof authGetMeMutator>,signal?: AbortSignal
) => {
      
      
      return authGetMeMutator<CurrentUserDto>(
      {url: `/auth/me`, method: 'GET', signal
    },
      options);
    }
  

export const getAuthGetMeQueryKey = () => {
    return [`/auth/me`] as const;
    }

    
export const getAuthGetMeQueryOptions = <TData = Awaited<ReturnType<typeof authGetMe>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGetMe>>, TError, TData>>, request?: SecondParameter<typeof authGetMeMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthGetMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authGetMe>>> = ({ signal }) => authGetMe(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authGetMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthGetMeQueryResult = NonNullable<Awaited<ReturnType<typeof authGetMe>>>
export type AuthGetMeQueryError = void


export function useAuthGetMe<TData = Awaited<ReturnType<typeof authGetMe>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGetMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authGetMe>>,
          TError,
          Awaited<ReturnType<typeof authGetMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authGetMeMutator>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthGetMe<TData = Awaited<ReturnType<typeof authGetMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGetMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authGetMe>>,
          TError,
          Awaited<ReturnType<typeof authGetMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authGetMeMutator>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthGetMe<TData = Awaited<ReturnType<typeof authGetMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGetMe>>, TError, TData>>, request?: SecondParameter<typeof authGetMeMutator>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAuthGetMe<TData = Awaited<ReturnType<typeof authGetMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGetMe>>, TError, TData>>, request?: SecondParameter<typeof authGetMeMutator>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthGetMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get onboarding state for the authenticated user
 */
export const onboardingGetStatus = (
    
 options?: SecondParameter<typeof onboardingGetStatusMutator>,signal?: AbortSignal
) => {
      
      
      return onboardingGetStatusMutator<OnboardingStatusDto>(
      {url: `/onboarding/status`, method: 'GET', signal
    },
      options);
    }
  

export const getOnboardingGetStatusQueryKey = () => {
    return [`/onboarding/status`] as const;
    }

    
export const getOnboardingGetStatusQueryOptions = <TData = Awaited<ReturnType<typeof onboardingGetStatus>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof onboardingGetStatus>>, TError, TData>>, request?: SecondParameter<typeof onboardingGetStatusMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOnboardingGetStatusQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof onboardingGetStatus>>> = ({ signal }) => onboardingGetStatus(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof onboardingGetStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OnboardingGetStatusQueryResult = NonNullable<Awaited<ReturnType<typeof onboardingGetStatus>>>
export type OnboardingGetStatusQueryError = void


export function useOnboardingGetStatus<TData = Awaited<ReturnType<typeof onboardingGetStatus>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof onboardingGetStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof onboardingGetStatus>>,
          TError,
          Awaited<ReturnType<typeof onboardingGetStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof onboardingGetStatusMutator>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOnboardingGetStatus<TData = Awaited<ReturnType<typeof onboardingGetStatus>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof onboardingGetStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof onboardingGetStatus>>,
          TError,
          Awaited<ReturnType<typeof onboardingGetStatus>>
        > , 'initialData'
      >, request?: SecondParameter<typeof onboardingGetStatusMutator>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOnboardingGetStatus<TData = Awaited<ReturnType<typeof onboardingGetStatus>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof onboardingGetStatus>>, TError, TData>>, request?: SecondParameter<typeof onboardingGetStatusMutator>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get onboarding state for the authenticated user
 */

export function useOnboardingGetStatus<TData = Awaited<ReturnType<typeof onboardingGetStatus>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof onboardingGetStatus>>, TError, TData>>, request?: SecondParameter<typeof onboardingGetStatusMutator>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOnboardingGetStatusQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create first study plan from onboarding wizard input
 */
export const onboardingCreateStudyPlan = (
    createOnboardingStudyPlanRequestDto: CreateOnboardingStudyPlanRequestDto,
 options?: SecondParameter<typeof onboardingCreateStudyPlanMutator>,signal?: AbortSignal
) => {
      
      
      return onboardingCreateStudyPlanMutator<CreateOnboardingStudyPlanResponseDto>(
      {url: `/onboarding/study-plans`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createOnboardingStudyPlanRequestDto, signal
    },
      options);
    }
  


export const getOnboardingCreateStudyPlanMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof onboardingCreateStudyPlan>>, TError,{data: CreateOnboardingStudyPlanRequestDto}, TContext>, request?: SecondParameter<typeof onboardingCreateStudyPlanMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof onboardingCreateStudyPlan>>, TError,{data: CreateOnboardingStudyPlanRequestDto}, TContext> => {
    
const mutationKey = ['onboardingCreateStudyPlan'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof onboardingCreateStudyPlan>>, {data: CreateOnboardingStudyPlanRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  onboardingCreateStudyPlan(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OnboardingCreateStudyPlanMutationResult = NonNullable<Awaited<ReturnType<typeof onboardingCreateStudyPlan>>>
    export type OnboardingCreateStudyPlanMutationBody = CreateOnboardingStudyPlanRequestDto
    export type OnboardingCreateStudyPlanMutationError = void

    /**
 * @summary Create first study plan from onboarding wizard input
 */
export const useOnboardingCreateStudyPlan = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof onboardingCreateStudyPlan>>, TError,{data: CreateOnboardingStudyPlanRequestDto}, TContext>, request?: SecondParameter<typeof onboardingCreateStudyPlanMutator>}
): UseMutationResult<
        Awaited<ReturnType<typeof onboardingCreateStudyPlan>>,
        TError,
        {data: CreateOnboardingStudyPlanRequestDto},
        TContext
      > => {

      const mutationOptions = getOnboardingCreateStudyPlanMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Repace unfinished learning units without touching completed progress
 */
export const studyPlansRepace = (
    id: string,
    repaceStudyPlanRequestDto: RepaceStudyPlanRequestDto,
 options?: SecondParameter<typeof studyPlansRepaceMutator>,signal?: AbortSignal
) => {
      
      
      return studyPlansRepaceMutator<RepaceStudyPlanResponseDto>(
      {url: `/study-plans/${id}/repace`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: repaceStudyPlanRequestDto, signal
    },
      options);
    }
  


export const getStudyPlansRepaceMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof studyPlansRepace>>, TError,{id: string;data: RepaceStudyPlanRequestDto}, TContext>, request?: SecondParameter<typeof studyPlansRepaceMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof studyPlansRepace>>, TError,{id: string;data: RepaceStudyPlanRequestDto}, TContext> => {
    
const mutationKey = ['studyPlansRepace'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof studyPlansRepace>>, {id: string;data: RepaceStudyPlanRequestDto}> = (props) => {
          const {id,data} = props ?? {};

          return  studyPlansRepace(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StudyPlansRepaceMutationResult = NonNullable<Awaited<ReturnType<typeof studyPlansRepace>>>
    export type StudyPlansRepaceMutationBody = RepaceStudyPlanRequestDto
    export type StudyPlansRepaceMutationError = void

    /**
 * @summary Repace unfinished learning units without touching completed progress
 */
export const useStudyPlansRepace = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof studyPlansRepace>>, TError,{id: string;data: RepaceStudyPlanRequestDto}, TContext>, request?: SecondParameter<typeof studyPlansRepaceMutator>}
): UseMutationResult<
        Awaited<ReturnType<typeof studyPlansRepace>>,
        TError,
        {id: string;data: RepaceStudyPlanRequestDto},
        TContext
      > => {

      const mutationOptions = getStudyPlansRepaceMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Health check
 */
export const healthGetHealth = (
    
 options?: SecondParameter<typeof healthGetHealthMutator>,signal?: AbortSignal
) => {
      
      
      return healthGetHealthMutator<HealthGetHealth200>(
      {url: `/health`, method: 'GET', signal
    },
      options);
    }
  

export const getHealthGetHealthQueryKey = () => {
    return [`/health`] as const;
    }

    
export const getHealthGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof healthGetHealth>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>>, request?: SecondParameter<typeof healthGetHealthMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthGetHealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthGetHealth>>> = ({ signal }) => healthGetHealth(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthGetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof healthGetHealth>>>
export type HealthGetHealthQueryError = unknown


export function useHealthGetHealth<TData = Awaited<ReturnType<typeof healthGetHealth>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthGetHealth>>,
          TError,
          Awaited<ReturnType<typeof healthGetHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof healthGetHealthMutator>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthGetHealth<TData = Awaited<ReturnType<typeof healthGetHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthGetHealth>>,
          TError,
          Awaited<ReturnType<typeof healthGetHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof healthGetHealthMutator>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthGetHealth<TData = Awaited<ReturnType<typeof healthGetHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>>, request?: SecondParameter<typeof healthGetHealthMutator>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health check
 */

export function useHealthGetHealth<TData = Awaited<ReturnType<typeof healthGetHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>>, request?: SecondParameter<typeof healthGetHealthMutator>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthGetHealthQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




