/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Textbooked Backend API
 * Backend MVP API for textbook study planning and grading.
 * OpenAPI spec version: 1.0.0
 */
import type {
  CreateOnboardingStudyPlanRequestDto,
  CreateOnboardingStudyPlanResponseDto,
  CurrentUserDto,
  HealthGetHealth200,
  OnboardingStatusDto,
  RepaceStudyPlanRequestDto,
  RepaceStudyPlanResponseDto
} from '../schemas';

import authGetMeMutator from '../axios';
import onboardingGetStatusMutator from '../axios';
import onboardingCreateStudyPlanMutator from '../axios';
import studyPlansRepaceMutator from '../axios';
import healthGetHealthMutator from '../axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];


  export const getTextbookedBackendAPI = () => {
const authGetMe = (
    
 options?: SecondParameter<typeof authGetMeMutator>,) => {
      return authGetMeMutator<CurrentUserDto>(
      {url: `/auth/me`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Get onboarding state for the authenticated user
 */
const onboardingGetStatus = (
    
 options?: SecondParameter<typeof onboardingGetStatusMutator>,) => {
      return onboardingGetStatusMutator<OnboardingStatusDto>(
      {url: `/onboarding/status`, method: 'GET'
    },
      options);
    }
  
/**
 * @summary Create first study plan from onboarding wizard input
 */
const onboardingCreateStudyPlan = (
    createOnboardingStudyPlanRequestDto: CreateOnboardingStudyPlanRequestDto,
 options?: SecondParameter<typeof onboardingCreateStudyPlanMutator>,) => {
      return onboardingCreateStudyPlanMutator<CreateOnboardingStudyPlanResponseDto>(
      {url: `/onboarding/study-plans`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: createOnboardingStudyPlanRequestDto
    },
      options);
    }
  
/**
 * @summary Repace unfinished learning units without touching completed progress
 */
const studyPlansRepace = (
    id: string,
    repaceStudyPlanRequestDto: RepaceStudyPlanRequestDto,
 options?: SecondParameter<typeof studyPlansRepaceMutator>,) => {
      return studyPlansRepaceMutator<RepaceStudyPlanResponseDto>(
      {url: `/study-plans/${id}/repace`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: repaceStudyPlanRequestDto
    },
      options);
    }
  
/**
 * @summary Health check
 */
const healthGetHealth = (
    
 options?: SecondParameter<typeof healthGetHealthMutator>,) => {
      return healthGetHealthMutator<HealthGetHealth200>(
      {url: `/health`, method: 'GET'
    },
      options);
    }
  
return {authGetMe,onboardingGetStatus,onboardingCreateStudyPlan,studyPlansRepace,healthGetHealth}};
export type AuthGetMeResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTextbookedBackendAPI>['authGetMe']>>>
export type OnboardingGetStatusResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTextbookedBackendAPI>['onboardingGetStatus']>>>
export type OnboardingCreateStudyPlanResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTextbookedBackendAPI>['onboardingCreateStudyPlan']>>>
export type StudyPlansRepaceResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTextbookedBackendAPI>['studyPlansRepace']>>>
export type HealthGetHealthResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getTextbookedBackendAPI>['healthGetHealth']>>>
