/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Textbooked Backend API
 * Backend MVP API for textbook study planning and grading.
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CurrentUserDto,
  HealthGetHealth200,
  RepaceStudyPlanRequestDto,
  RepaceStudyPlanResponseDto
} from '../schemas';

import authGetMeMutator from '../axios';
import studyPlanRepaceMutator from '../axios';
import healthGetHealthMutator from '../axios';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const authGetMe = (
    
 options?: SecondParameter<typeof authGetMeMutator>,signal?: AbortSignal
) => {
      
      
      return authGetMeMutator<CurrentUserDto>(
      {url: `/auth/me`, method: 'GET', signal
    },
      options);
    }
  

export const getAuthGetMeQueryKey = () => {
    return [`/auth/me`] as const;
    }

    
export const getAuthGetMeQueryOptions = <TData = Awaited<ReturnType<typeof authGetMe>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGetMe>>, TError, TData>>, request?: SecondParameter<typeof authGetMeMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuthGetMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof authGetMe>>> = ({ signal }) => authGetMe(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof authGetMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AuthGetMeQueryResult = NonNullable<Awaited<ReturnType<typeof authGetMe>>>
export type AuthGetMeQueryError = void


export function useAuthGetMe<TData = Awaited<ReturnType<typeof authGetMe>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGetMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authGetMe>>,
          TError,
          Awaited<ReturnType<typeof authGetMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authGetMeMutator>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthGetMe<TData = Awaited<ReturnType<typeof authGetMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGetMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authGetMe>>,
          TError,
          Awaited<ReturnType<typeof authGetMe>>
        > , 'initialData'
      >, request?: SecondParameter<typeof authGetMeMutator>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAuthGetMe<TData = Awaited<ReturnType<typeof authGetMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGetMe>>, TError, TData>>, request?: SecondParameter<typeof authGetMeMutator>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAuthGetMe<TData = Awaited<ReturnType<typeof authGetMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof authGetMe>>, TError, TData>>, request?: SecondParameter<typeof authGetMeMutator>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAuthGetMeQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Repace unfinished learning units without touching completed progress
 */
export const studyPlanRepace = (
    id: string,
    repaceStudyPlanRequestDto: RepaceStudyPlanRequestDto,
 options?: SecondParameter<typeof studyPlanRepaceMutator>,signal?: AbortSignal
) => {
      
      
      return studyPlanRepaceMutator<RepaceStudyPlanResponseDto>(
      {url: `/study-plans/${id}/repace`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: repaceStudyPlanRequestDto, signal
    },
      options);
    }
  


export const getStudyPlanRepaceMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof studyPlanRepace>>, TError,{id: string;data: RepaceStudyPlanRequestDto}, TContext>, request?: SecondParameter<typeof studyPlanRepaceMutator>}
): UseMutationOptions<Awaited<ReturnType<typeof studyPlanRepace>>, TError,{id: string;data: RepaceStudyPlanRequestDto}, TContext> => {
    
const mutationKey = ['studyPlanRepace'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof studyPlanRepace>>, {id: string;data: RepaceStudyPlanRequestDto}> = (props) => {
          const {id,data} = props ?? {};

          return  studyPlanRepace(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type StudyPlanRepaceMutationResult = NonNullable<Awaited<ReturnType<typeof studyPlanRepace>>>
    export type StudyPlanRepaceMutationBody = RepaceStudyPlanRequestDto
    export type StudyPlanRepaceMutationError = void

    /**
 * @summary Repace unfinished learning units without touching completed progress
 */
export const useStudyPlanRepace = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof studyPlanRepace>>, TError,{id: string;data: RepaceStudyPlanRequestDto}, TContext>, request?: SecondParameter<typeof studyPlanRepaceMutator>}
): UseMutationResult<
        Awaited<ReturnType<typeof studyPlanRepace>>,
        TError,
        {id: string;data: RepaceStudyPlanRequestDto},
        TContext
      > => {

      const mutationOptions = getStudyPlanRepaceMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Health check
 */
export const healthGetHealth = (
    
 options?: SecondParameter<typeof healthGetHealthMutator>,signal?: AbortSignal
) => {
      
      
      return healthGetHealthMutator<HealthGetHealth200>(
      {url: `/health`, method: 'GET', signal
    },
      options);
    }
  

export const getHealthGetHealthQueryKey = () => {
    return [`/health`] as const;
    }

    
export const getHealthGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof healthGetHealth>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>>, request?: SecondParameter<typeof healthGetHealthMutator>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthGetHealthQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthGetHealth>>> = ({ signal }) => healthGetHealth(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthGetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof healthGetHealth>>>
export type HealthGetHealthQueryError = unknown


export function useHealthGetHealth<TData = Awaited<ReturnType<typeof healthGetHealth>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthGetHealth>>,
          TError,
          Awaited<ReturnType<typeof healthGetHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof healthGetHealthMutator>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthGetHealth<TData = Awaited<ReturnType<typeof healthGetHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthGetHealth>>,
          TError,
          Awaited<ReturnType<typeof healthGetHealth>>
        > , 'initialData'
      >, request?: SecondParameter<typeof healthGetHealthMutator>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthGetHealth<TData = Awaited<ReturnType<typeof healthGetHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>>, request?: SecondParameter<typeof healthGetHealthMutator>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Health check
 */

export function useHealthGetHealth<TData = Awaited<ReturnType<typeof healthGetHealth>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthGetHealth>>, TError, TData>>, request?: SecondParameter<typeof healthGetHealthMutator>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthGetHealthQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




