/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Textbooked Backend API
 * Backend MVP API for textbook study planning and grading.
 * OpenAPI spec version: 1.0.0
 */
import type { AdminSortDtoOrder } from './adminSortDtoOrder';

export interface AdminSortDto {
  field: string;
  order: AdminSortDtoOrder;
}
