/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Textbooked Backend API
 * Backend MVP API for textbook study planning and grading.
 * OpenAPI spec version: 1.0.0
 */
import type { StudyPlanMode } from './studyPlanMode';
import type { OnboardingLevel } from './onboardingLevel';
import type { OnboardingSourceInputDto } from './onboardingSourceInputDto';
import type { OnboardingBackgroundInputDto } from './onboardingBackgroundInputDto';

export interface CreateOnboardingStudyPlanRequestDto {
  mode: StudyPlanMode;
  goalPrompt: string;
  /**
   * @minimum 1
   * @maximum 5
   */
  intensity: number;
  category?: string;
  level?: OnboardingLevel;
  /** Required when mode is SOURCE_FOCUSED. */
  source?: OnboardingSourceInputDto;
  background: OnboardingBackgroundInputDto;
}
