/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Textbooked Backend API
 * Backend MVP API for textbook study planning and grading.
 * OpenAPI spec version: 1.0.0
 */

export type CurrentAdminUserDtoRole = typeof CurrentAdminUserDtoRole[keyof typeof CurrentAdminUserDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CurrentAdminUserDtoRole = {
  ADMIN: 'ADMIN',
  SUPER_ADMIN: 'SUPER_ADMIN',
} as const;
