/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Textbooked Backend API
 * Backend MVP API for textbook study planning and grading.
 * OpenAPI spec version: 1.0.0
 */
import type { CurrentUserDtoName } from './currentUserDtoName';
import type { CurrentUserDtoImage } from './currentUserDtoImage';
import type { CurrentUserDtoFirstName } from './currentUserDtoFirstName';
import type { CurrentUserDtoLastName } from './currentUserDtoLastName';

export interface CurrentUserDto {
  id: string;
  email: string;
  /** @nullable */
  name: CurrentUserDtoName;
  /** @nullable */
  image: CurrentUserDtoImage;
  /** @nullable */
  firstName?: CurrentUserDtoFirstName;
  /** @nullable */
  lastName?: CurrentUserDtoLastName;
}
