/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Textbooked Backend API
 * Backend MVP API for textbook study planning and grading.
 * OpenAPI spec version: 1.0.0
 */
import type { CurrentAdminUserDtoName } from './currentAdminUserDtoName';
import type { CurrentAdminUserDtoImage } from './currentAdminUserDtoImage';
import type { CurrentAdminUserDtoFirstName } from './currentAdminUserDtoFirstName';
import type { CurrentAdminUserDtoLastName } from './currentAdminUserDtoLastName';
import type { CurrentAdminUserDtoRole } from './currentAdminUserDtoRole';

export interface CurrentAdminUserDto {
  id: string;
  authSub: string;
  email: string;
  name?: CurrentAdminUserDtoName;
  image?: CurrentAdminUserDtoImage;
  firstName?: CurrentAdminUserDtoFirstName;
  lastName?: CurrentAdminUserDtoLastName;
  role: CurrentAdminUserDtoRole;
  isActive: boolean;
}
