/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Textbooked Backend API
 * Backend MVP API for textbook study planning and grading.
 * OpenAPI spec version: 1.0.0
 */

export type Pace = typeof Pace[keyof typeof Pace];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Pace = {
  CHILL: 'CHILL',
  NORMAL: 'NORMAL',
  INTENSE: 'INTENSE',
  MASTER: 'MASTER',
} as const;
