/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Textbooked Backend API
 * Backend MVP API for textbook study planning and grading.
 * OpenAPI spec version: 1.0.0
 */

export interface RepaceStudyPlanRequestDto {
  /**
   * Optional new plan intensity.
   * @minimum 1
   * @maximum 5
   */
  intensity?: number;
  /** Optional new start date for unfinished units. */
  startDate?: string;
}
