/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * Textbooked Backend API
 * Backend MVP API for textbook study planning and grading.
 * OpenAPI spec version: 1.0.0
 */
import type { StudyPlanMode } from './studyPlanMode';
import type { Pace } from './pace';

export interface RepaceStudyPlanResponseDto {
  studyPlanId: string;
  mode: StudyPlanMode;
  intensity: number;
  pace: Pace;
  effectiveStartDate: string;
  pendingUnits: number;
  completedUnits: number;
  sectionsRelaidOut: number;
}
